name: Release

on:
  workflow_call:

jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Release Changelog
      run: npx changelogithub
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
